#ifndef REAKTOR_A11Y_PUBLIC_H
#define REAKTOR_A11Y_PUBLIC_H

enum {
    REAKTOR_A11Y_NONE = 0,
    REAKTOR_A11Y_WINDOW,
    REAKTOR_A11Y_GROUP,
    REAKTOR_A11Y_TABLIST,
    REAKTOR_A11Y_TAB,
    REAKTOR_A11Y_BUTTON,
    REAKTOR_A11Y_LINK,
    REAKTOR_A11Y_CHECKBOX,
    REAKTOR_A11Y_RADIO,
    REAKTOR_A11Y_TEXTBOX,
    REAKTOR_A11Y_SLIDER,
    REAKTOR_A11Y_SPINBUTTON,
    REAKTOR_A11Y_PROGRESS,
    REAKTOR_A11Y_COMBOBOX,
    REAKTOR_A11Y_LISTITEM,
    REAKTOR_A11Y_TREEITEM,
    REAKTOR_A11Y_MENUBAR,
    REAKTOR_A11Y_MENU,
    REAKTOR_A11Y_MENUITEM,
    REAKTOR_A11Y_DIALOG,
    REAKTOR_A11Y_LABEL,
    REAKTOR_A11Y_ROLE_COUNT
};

enum {
    REAKTOR_A11Y_FOCUSED   = 1u << 0,
    REAKTOR_A11Y_CHECKED   = 1u << 1,
    REAKTOR_A11Y_EXPANDED  = 1u << 2,
    REAKTOR_A11Y_SELECTED  = 1u << 3,
    REAKTOR_A11Y_DISABLED  = 1u << 4,
    REAKTOR_A11Y_OFFSCREEN = 1u << 6,
    REAKTOR_A11Y_VOLATILE  = 1u << 7
};

#endif
